// Automatically generated by the Tiger compiler, do NOT edit.

	.data
slp_format:
	.string "%d "
newline:
	.string "\n"
a:
	.int 0
b:
	.int 0


	.text
	.globl main
main:
	pushl	%ebp
	movl	%esp, %ebp
	movl	$3, %eax
	pushl	%eax
	movl	$5, %eax
	popl	%edx
	addl	%edx, %eax
	movl	%eax, a
	movl	a, %eax
	pushl	%eax
	pushl	$slp_format
	call	printf
	addl	$4, %esp
	movl	a, %eax
	pushl	%eax
	movl	$1, %eax
	popl	%edx
	subl	%eax, %edx
	movl	%edx, %eax
	pushl	%eax
	pushl	$slp_format
	call	printf
	addl	$4, %esp
	pushl	$newline
	call	printf
	addl	$4, %esp
	movl	$10, %eax
	pushl	%eax
	movl	a, %eax
	popl	%edx
	imul	%edx
	movl	%eax, b
	movl	b, %eax
	pushl	%eax
	pushl	$slp_format
	call	printf
	addl	$4, %esp
	pushl	$newline
	call	printf
	addl	$4, %esp
	leave
	ret

