
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 19 17:10:08 CST 2017
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 30;
  public static final int LPAREN = 32;
  public static final int MINUS = 22;
  public static final int STATIC = 12;
  public static final int RPAREN = 33;
  public static final int SEMICOLON = 36;
  public static final int NOT = 27;
  public static final int AND = 24;
  public static final int LT = 25;
  public static final int COMMA = 29;
  public static final int CLASS = 9;
  public static final int PLUS = 21;
  public static final int MAIN = 14;
  public static final int IF = 5;
  public static final int THIS = 17;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int RBRACKET = 31;
  public static final int TRUE = 15;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int BECOMES = 26;
  public static final int VOID = 13;
  public static final int INTEGER_TYPE = 3;
  public static final int TIMES = 23;
  public static final int LBRACE = 34;
  public static final int ELSE = 6;
  public static final int SYSTEM_OUT_PRINTLN = 20;
  public static final int WHILE = 7;
  public static final int PUBLIC = 11;
  public static final int RBRACE = 35;
  public static final int EXTENDS = 10;
  public static final int STRING = 4;
  public static final int FALSE = 16;
  public static final int LENGTH = 18;
  public static final int INTEGER_LITERAL = 38;
  public static final int IDENTIFIER = 37;
  public static final int BOOLEAN_TYPE = 2;
}

