
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 08 22:52:53 CST 2017
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 21;
  public static final int AND_AND = 23;
  public static final int LPAREN = 26;
  public static final int INT = 10;
  public static final int MINUS = 20;
  public static final int STATIC = 5;
  public static final int RPAREN = 27;
  public static final int BOOLEAN_LITERAL = 36;
  public static final int NOT = 24;
  public static final int SEMICOLON = 32;
  public static final int LT = 22;
  public static final int COMMA = 33;
  public static final int CLASS = 3;
  public static final int PLUS = 19;
  public static final int MAIN = 7;
  public static final int IF = 12;
  public static final int THIS = 17;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RETURN = 2;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int VOID = 6;
  public static final int EQ = 25;
  public static final int LBRACK = 30;
  public static final int LBRACE = 28;
  public static final int ELSE = 13;
  public static final int SYSTEM_OUT_PRINTLN = 15;
  public static final int RBRACK = 31;
  public static final int WHILE = 14;
  public static final int PUBLIC = 4;
  public static final int RBRACE = 29;
  public static final int EXTENDS = 8;
  public static final int STRING = 9;
  public static final int LENGTH = 16;
  public static final int INTEGER_LITERAL = 37;
  public static final int IDENTIFIER = 35;
}

